### PR TITLE
Initial Linux support

### PR DESCRIPTION
**Pull request by Scotsguy**
Works as far as creating a seed, creating the .pak, and playing the randomized seed (see screenshot).

There are some buttons that call explorer.exe that won't work yet, neither will launching the game from within rando. I think there's an xdg-open crate that could handle that.

I replaced the simple static linked oodle library with the implementation by the repak crate (a different part of which was already in use). Note that it seems to download the library at runtime (from Warframe's servers..?), which I think is kind of suboptimal. However, it does manage to wrangle it into working on Linux at least.

### CODE REVIEW

**Comment by bananaturtlesandwich** [comment]
i thought pseudoregalia only had a windows build?

**Comment by bananaturtlesandwich** [comment]
also the reason i statically link it is because nexus took it down when it used a web request

**Comment by bananaturtlesandwich** [comment]
i have the static libs for linux i just can't build for linux because they like to make cross compilation from windows a pain in the ass

**Comment by Scotsguy** [comment]
> i thought pseudoregalia only had a windows build?

It only has a windows build, but works perfectly with Proton, and while rando works when run with the system's wine, a native build is easier/more convenient to run.

> also the reason i statically link it is because nexus took it down when it used a web request

I see. Maybe I can figure out a way to vendor it, then.

**Comment by bananaturtlesandwich** [comment]
okay just set up windows subsystem for linux and only needed 2 changes to allow compilation https://github.com/pseudoregalia-modding/rando/commit/941e55da5b418c384a34c3f1cd3823946a1120ac so the next release will have a linux build :)

**Comment by Scotsguy** [comment]
Nice, that's a better solution. Thanks!

**Pull request closed without merging**
